# -*- coding: utf-8 -*-
"""Untitled155.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I1wgo2z0C8rTODBR_n2YLd7bmY_5xh9u
"""

print("Qadamova Zulayho")